-- 1. Tabel Profil (Sudah ada referensi di middleware)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  role text default 'user',
  photo_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Tabel Produk
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  unit text default 'pcs',
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Tabel Klien
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  phone text,
  email text,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Tabel Penawaran (Quotes)
create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  no text unique not null,
  client_name text,
  date date default current_date,
  status text default 'Pending',
  type text,
  discount numeric default 0,
  tax numeric default 11,
  notes text,
  location text,
  payment_term text,
  items jsonb not null, -- Menyimpan array item penawaran
  attachments jsonb default '[]', -- Menyimpan array URL lampiran pengerjaan
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Tabel Invoice
create table if not exists public.invoices (
  id bigint generated by default as identity primary key,
  no text unique not null,
  quote_ref text, -- Referensi nomor penawaran
  client_name text,
  date date default current_date,
  due_date date,
  status text default 'Belum Dibayar',
  type text,
  discount numeric default 0,
  tax numeric default 11,
  notes text,
  location text,
  payment_term text,
  items jsonb not null,
  attachments jsonb default '[]', -- Menyimpan array URL bukti pengerjaan selesai
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Aktifkan RLS (Row Level Security)
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.clients enable row level security;
alter table public.quotes enable row level security;
alter table public.invoices enable row level security;
-- Tambahkan kebijakan RLS sesuai kebutuhan (Admin only, dll)